package com.demospace.demoproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DemoModel implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DemoModel() {
    }




}