package com.demospace.demoproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DemoModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public DemoModel() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public DemoModel(java.lang.String name) {
		this.name = name;
	}

}